### ISSUE TITLE
HPOS compatibility

### ISSUE THREAD

**Issue by costingheonea** [AashikP/item-total-for-wc#5]
Hi,
Will you update this plugin with HPOS compatibility?

**Comment by AashikP** [comment]
@costingheonea 

Sorry for the delayed response here as I was away for a while.

Thank you for opening this issue. The extension now supports HPOS. Find the latest version here:  [Version 1.3.0](https://github.com/AashikP/item-total-for-wc/releases/tag/v1.3.0)

I've tested this on a couple of my test sites, but I'd strongly recommend testing this on a Staging site first before installing it on a production/live site.
